#pragma once

#define MYICON 100

#define IDBITMAP_OPENINGSCENE 101

#define IDBITMAP_MOUNTAIN 102
#define IDBITMAP_BACKGROUND 103
#define IDBITMAP_SUN 104
#define IDBITMAP_TREE 105
#define IDBITMAP_CLOUD 106
#define IDBITMAP_GRASS 107
#define IDBITMAP_HOME 108
#define IDBITMAP_DOOR 109
#define IDBITMAP_WINDOW 110
#define IDBITMAP_BRANCH 111
#define IDBITMAP_BIRDFOOD 112

#define IDBITMAP_PHOTO1 113
#define IDBITMAP_PHOTO2 114
#define IDBITMAP_PHOTO3 115
#define IDBITMAP_PHOTO4 116

void Enqueue(LONGLONG);
LARGE_INTEGER Dequeue(void);
void DisplayQueue(void);




